colossus/apps/lists/urls.py
# flake8: noqa

from django.urls import path

from . import views

app_name = "mailing"


urlpatterns = [
    path("", views.MailingListListView.as_view(), name="lists"),
    path("add/", views.MailingListCreateView.as_view(), name="new_list"),
    path("<int:pk>/", views.MailingListDetailView.as_view(), name="list"),
    path(
        "<int:pk>/locations/<str:country_code>/",
        views.MailingListCountryReportView.as_view(),
        name="country_report",
    ),
    path(
        "<int:pk>/subscribers/", views.SubscriberListView.as_view(), name="subscribers"
    ),
    path(
        "<int:pk>/subscribers/add/",
        views.SubscriberCreateView.as_view(),
        name="new_subscriber",
    ),
    path(
        "<int:pk>/subscribers/import/",
        views.ImportSubscribersView.as_view(),
        name="import_subscribers",
    ),
    path(
        "<int:pk>/subscribers/import/csv/",
        views.SubscriberImportView.as_view(),
        name="csv_import_subscribers",
    ),
    path(
        "<int:pk>/subscribers/import/csv/<int:import_pk>/",
        views.SubscriberImportPreviewView.as_view(),
        name="import_preview",
    ),
    path(
        "<int:pk>/subscribers/import/csv/<int:import_pk>/queued/",
        views.SubscriberImportQueuedView.as_view(),
        name="import_queued",
    ),
    path(
        "<int:pk>/subscribers/import/csv/<int:import_pk>/download/",
        views.download_subscriber_import,
        name="download_subscriber_import",
    ),
    path(
        "<int:pk>/subscribers/import/csv/<int:import_pk>/delete/",
        views.SubscriberImportDeleteView.as_view(),
        name="delete_subscriber_import",
    ),
    path(
        "<int:pk>/subscribers/import/paste/",
        views.PasteEmailsImportSubscribersView.as_view(),
        name="paste_import_subscribers",
    ),
    path(
        "<int:pk>/subscribers/<int:subscriber_pk>/",
        views.SubscriberDetailView.as_view(),
        name="subscriber",
    ),
    path(
        "<int:pk>/subscribers/<int:subscriber_pk>/edit/",
        views.SubscriberUpdateView.as_view(),
        name="edit_subscriber",
    ),
    path(
        "<int:pk>/subscribers/<int:subscriber_pk>/delete/",
        views.SubscriberDeleteView.as_view(),
        name="delete_subscriber",
    ),
    path("<int:pk>/tags/", views.TagListView.as_view(), name="tags"),
    path("<int:pk>/tags/add/", views.TagCreateView.as_view(), name="new_tag"),
    path(
        "<int:pk>/tags/bulk-tag/",
        views.BulkTagSubscribersView.as_view(),
        name="bulk_tag",
    ),
    path(
        "<int:pk>/tags/<int:tag_pk>/edit/",
        views.TagUpdateView.as_view(),
        name="edit_tag",
    ),
    path(
        "<int:pk>/tags/<int:tag_pk>/delete/",
        views.TagDeleteView.as_view(),
        name="delete_tag",
    ),
    path(
        "<int:pk>/forms/",
        views.SubscriptionFormsView.as_view(),
        name="subscription_forms",
    ),
    path(
        "<int:pk>/forms/editor/", views.FormsEditorView.as_view(), name="forms_editor"
    ),
    path(
        "<int:pk>/forms/editor/design/",
        views.CustomizeDesignView.as_view(),
        name="customize_design",
    ),
    path(
        "<int:pk>/forms/editor/<str:form_key>/",
        views.SubscriptionFormTemplateUpdateView.as_view(),
        name="edit_form_template",
    ),
    path(
        "<int:pk>/forms/editor/<str:form_key>/preview/",
        views.PreviewFormTemplateView.as_view(),
        name="preview_form_template",
    ),
    path(
        "<int:pk>/forms/editor/<str:form_key>/reset/",
        views.ResetFormTemplateView.as_view(),
        name="reset_form_template",
    ),
    path("<int:pk>/settings/", views.ListSettingsView.as_view(), name="settings"),
    path(
        "<int:pk>/settings/subscription/",
        views.SubscriptionSettingsView.as_view(),
        name="subscription_settings",
    ),
    path(
        "<int:pk>/settings/defaults/",
        views.CampaignDefaultsView.as_view(),
        name="defaults",
    ),
    path("<int:pk>/settings/smtp/", views.SMTPCredentialsView.as_view(), name="smtp"),
    path(
        "<int:pk>/charts/subscriptions/",
        views.SubscriptionsSummaryChartView.as_view(),
        name="charts_subscriptions_summary",
    ),
    path(
        "<int:pk>/charts/domains/",
        views.ListDomainsChartView.as_view(),
        name="charts_list_domains",
    ),
    path(
        "<int:pk>/charts/locations/",
        views.ListLocationsChartView.as_view(),
        name="charts_list_locations",
    ),
]

colossus/apps/subscribers/urls.py
from django.urls import path

from . import views

app_name = "subscribers"


urlpatterns = [
    path("manage/", views.manage, name="manage"),
    path("goodbye/<uuid:mailing_list_uuid>/", views.goodbye, name="goodbye"),
    path("subscribe/<uuid:mailing_list_uuid>/", views.subscribe, name="subscribe"),
    path(
        "subscribe/<uuid:mailing_list_uuid>/confirm/",
        views.confirm_subscription,
        name="confirm_subscription",
    ),
    path(
        "subscribe/<uuid:mailing_list_uuid>/confirm/<str:token>/",
        views.confirm_double_optin_token,
        name="confirm_double_optin_token",
    ),  # noqa
    path(
        "unsubscribe/<uuid:mailing_list_uuid>/",
        views.unsubscribe_manual,
        name="unsubscribe_manual",
    ),
    path(
        "unsubscribe/<uuid:mailing_list_uuid>/<uuid:subscriber_uuid>/<uuid:campaign_uuid>/",
        views.unsubscribe,
        name="unsubscribe",
    ),  # noqa
    path(
        "track/open/<uuid:email_uuid>/<uuid:subscriber_uuid>/",
        views.track_open,
        name="open",
    ),
    path(
        "track/click/<uuid:link_uuid>/<uuid:subscriber_uuid>/",
        views.track_click,
        name="click",
    ),
]

colossus/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from colossus.apps.core import views as core_views

urlpatterns = [
    path("", core_views.dashboard, name="dashboard"),
    path("", include("colossus.apps.subscribers.urls", namespace="subscribers")),
    path("setup/", core_views.setup, name="setup"),
    path("setup/account/", core_views.setup_account, name="setup_account"),
    path("settings/", core_views.SiteUpdateView.as_view(), name="settings"),
    path("accounts/", include("colossus.apps.accounts.urls")),
    path("lists/", include("colossus.apps.lists.urls", namespace="lists")),
    path(
        "notifications/",
        include("colossus.apps.notifications.urls", namespace="notifications"),
    ),
    path("templates/", include("colossus.apps.templates.urls", namespace="templates")),
    path("campaigns/", include("colossus.apps.campaigns.urls", namespace="campaigns")),
    path(
        "<slug:mailing_list_slug>/",
        core_views.subscribe_shortcut,
        name="subscribe_shortcut",
    ),
    path(
        "<slug:mailing_list_slug>/unsubscribe/",
        core_views.unsubscribe_shortcut,
        name="unsubscribe_shortcut",
    ),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

colossus/apps/lists/models.py
import csv
import json
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Avg
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from colossus.apps.lists.constants import ImportStatus, ImportStrategies
from colossus.apps.subscribers.constants import Status, TemplateKeys
from colossus.storage import PrivateMediaStorage

User = get_user_model()


class MailingList(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(_("name"), max_length=100)
    slug = models.SlugField(_("list short URL"), max_length=100, unique=True)
    subscribers_count = models.PositiveIntegerField(_("subscribers"), default=0)
    open_rate = models.FloatField(_("opens"), default=0.0)
    click_rate = models.FloatField(_("clicks"), default=0.0)
    date_created = models.DateTimeField(_("created"), auto_now_add=True)
    contact_email_address = models.EmailField(_("contact email address"), blank=True)
    website_url = models.URLField(
        _("website URL"),
        blank=True,
        help_text=_("Where did people opt in to this list?"),
    )
    campaign_default_from_name = models.CharField(
        _("default from name"), max_length=100, blank=True
    )
    campaign_default_from_email = models.EmailField(
        _("default from email address"), blank=True
    )
    campaign_default_email_subject = models.CharField(
        _("default subject"), max_length=150, blank=True
    )
    enable_recaptcha = models.BooleanField(_("enable reCAPTCHA"), default=False)
    recaptcha_site_key = models.CharField(_("site key"), max_length=100, blank=True)
    recaptcha_secret_key = models.CharField(_("secret key"), max_length=100, blank=True)
    list_manager = models.EmailField(
        _("list manager"),
        blank=True,
        help_text=_(
            "Email address to handle subscribe/unsubscribe requests."
            "It can be a real email address or an automated route to handle callbacks/webhooks."
        ),
    )

    smtp_host = models.CharField(_("host"), max_length=200, blank=True)
    smtp_port = models.PositiveIntegerField(_("port"), blank=True, null=True)
    smtp_username = models.CharField(_("username"), max_length=200, blank=True)
    smtp_password = models.CharField(_("password"), max_length=200, blank=True)
    smtp_use_tls = models.BooleanField(_("use TLS"), default=True)
    smtp_use_ssl = models.BooleanField(_("use SSL"), default=False)
    smtp_timeout = models.PositiveIntegerField(_("timeout"), blank=True, null=True)
    smtp_ssl_keyfile = models.TextField(_("SSL keyfile"), blank=True)
    smtp_ssl_certfile = models.TextField(_("SSL certfile"), blank=True)

    forms_custom_css = models.TextField(
        _("custom CSS"),
        help_text=_("Custom CSS will be applied to all subscription form pages."),
        blank=True,
    )
    forms_custom_header = models.TextField(
        _("custom header"),
        help_text=_(
            "Header displayed on all subscription form pages. Accepts HTML."
            "If empty, the name of the mailing list will be used."
        ),
        blank=True,
    )

    class Meta:
        verbose_name = _("list")
        verbose_name_plural = _("lists")
        db_table = "colossus_mailing_lists"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("mailing:subscribers", kwargs={"pk": self.pk})

    def get_active_subscribers(self):
        return self.subscribers.filter(status=Status.SUBSCRIBED)

    def update_subscribers_count(self) -> int:
        self.subscribers_count = self.get_active_subscribers().count()
        self.save(update_fields=["subscribers_count"])
        return self.subscribers_count

    def update_click_rate(self) -> float:
        qs = (
            self.get_active_subscribers()
            .exclude(last_sent=None)
            .aggregate(Avg("click_rate"))
        )
        self.click_rate = round(qs.get("click_rate__avg", 0.9), 4)
        self.save(update_fields=["click_rate"])
        return self.click_rate

    def update_open_rate(self) -> float:
        qs = (
            self.get_active_subscribers()
            .exclude(last_sent=None)
            .aggregate(Avg("open_rate"))
        )
        self.open_rate = round(qs.get("open_rate__avg", 0.0), 4)
        self.save(update_fields=["open_rate"])
        return self.open_rate

    def update_open_and_click_rate(self):
        qs = (
            self.get_active_subscribers()
            .exclude(last_sent=None)
            .aggregate(open=Avg("open_rate"), click=Avg("click_rate"))
        )
        self.open_rate = round(qs.get("open", 0.0), 4)
        self.click_rate = round(qs.get("click", 0.0), 4)
        self.save(update_fields=["open_rate", "click_rate"])

    def _get_form_template(self, form_template_key: str):
        form_template, created = self.forms_templates.get_or_create(
            key=form_template_key
        )
        if created:
            form_template.load_defaults()
        return form_template

    def get_subscribe_form_template(self):
        return self._get_form_template(TemplateKeys.SUBSCRIBE_FORM)

    def get_subscribe_thank_you_page_template(self):
        return self._get_form_template(TemplateKeys.SUBSCRIBE_THANK_YOU_PAGE)

    def get_confirm_email_template(self):
        return self._get_form_template(TemplateKeys.CONFIRM_EMAIL)

    def get_confirm_thank_you_page_template(self):
        return self._get_form_template(TemplateKeys.CONFIRM_THANK_YOU_PAGE)

    def get_welcome_email_template(self):
        return self._get_form_template(TemplateKeys.WELCOME_EMAIL)

    def get_unsubscribe_form_template(self):
        return self._get_form_template(TemplateKeys.UNSUBSCRIBE_FORM)

    def get_unsubscribe_success_page_template(self):
        return self._get_form_template(TemplateKeys.UNSUBSCRIBE_SUCCESS_PAGE)

    def get_goodbye_email_template(self):
        return self._get_form_template(TemplateKeys.GOODBYE_EMAIL)


class SubscriberImport(models.Model):
    mailing_list = models.ForeignKey(
        MailingList,
        on_delete=models.CASCADE,
        related_name="subscribers_imports",
        verbose_name=_("mailing list"),
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        editable=False,
        related_name="subscribers_imports",
        verbose_name=_("user"),
    )
    upload_date = models.DateTimeField(_("upload date"), auto_now_add=True)
    file = models.FileField(
        _("CSV file"), upload_to="uploads", storage=PrivateMediaStorage()
    )
    columns_mapping = models.TextField(_("columns mapping"), blank=True)
    subscriber_status = models.PositiveSmallIntegerField(
        _("assign status to subscriber"),
        default=Status.SUBSCRIBED,
        choices=Status.CHOICES,
    )
    status = models.PositiveSmallIntegerField(
        _("status"), default=ImportStatus.PENDING, choices=ImportStatus.CHOICES
    )
    size = models.PositiveIntegerField(_("size"), default=0)
    strategy = models.PositiveSmallIntegerField(
        _("import strategy"),
        choices=ImportStrategies.CHOICES,
        default=ImportStrategies.UPDATE_OR_CREATE,
        help_text=_(
            "The email address will be used as the main subscriber identifier to determine if they are "
            "already on the list."
        ),
    )

    __cached_headings = None

    class Meta:
        verbose_name = _("subscribers import")
        verbose_name_plural = _("subscribers imports")
        db_table = "colossus_subscribers_imports"

    def delete(self, using=None, keep_parents=False):
        super().delete(using, keep_parents)
        self.file.delete(save=False)

    def set_columns_mapping(self, columns_mapping):
        self.columns_mapping = json.dumps(columns_mapping)

    def get_columns_mapping(self):
        try:
            columns_mapping = json.loads(self.columns_mapping)
        except (TypeError, json.JSONDecodeError):
            columns_mapping = dict()
        return {int(key): value for key, value in columns_mapping.items()}

    def get_headings(self):
        if self.__cached_headings is None:
            with open(self.file.path, "r") as csvfile:
                reader = csv.reader(csvfile)
                csv_headings = next(reader)
                self.__cached_headings = csv_headings
        return self.__cached_headings

    def get_str_headings(self):
        return ", ".join(self.get_headings())

    def get_rows(self, limit=None):
        rows = list()
        with open(self.file.path, "r") as csvfile:
            reader = csv.reader(csvfile)
            # skip header
            next(reader)
            for index, row in enumerate(reader):
                if index == limit:
                    break
                rows.append(row)
        return rows

    def get_preview(self):
        return self.get_rows(limit=10)

    def set_size(self, save=True):
        with open(self.file.path, "r") as csvfile:
            dialect = csv.Sniffer().sniff(csvfile.read(1024))
            csvfile.seek(0)
            reader = csv.reader(csvfile, dialect)
            self.size = sum(1 for row in reader)
        if save:
            self.save(update_fields=["size"])

colossus/apps/lists/templates/lists/base.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ mailing_list.name }}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'lists:lists' %}">{% trans 'Mailing Lists' %}</a></li>
      {% block innerbreadcrumb %}
        <li class="breadcrumb-item active" aria-current="page">{{ mailing_list.name }}</li>
      {% endblock %}
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ mailing_list.name }}
    <small class="text-muted">{{ mailing_list.get_active_subscribers.count }}</small>
  </h2>
  <div class="card mb-3">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link{% if submenu == 'details' %} active{% endif %}" href="{% url 'lists:list' mailing_list.pk %}">
            {% trans 'Summary' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if submenu == 'subscribers' %} active{% endif %}" href="{% url 'lists:subscribers' mailing_list.pk %}">
            {% trans 'Subscribers' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if submenu == 'tags' %} active{% endif %}" href="{% url 'lists:tags' mailing_list.pk %}">
            {% trans 'Tags' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if submenu == 'forms' %} active{% endif %}" href="{% url 'lists:subscription_forms' mailing_list.pk %}">
            {% trans 'Forms' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if submenu == 'settings' %} active{% endif %}" href="{% url 'lists:settings' mailing_list.pk %}">
            {% trans 'Settings' %}
          </a>
        </li>
      </ul>
    </div>
    {% block innercontent %}
    {% endblock %}
  </div>
  {% block outercontent %}
  {% endblock %}
{% endblock %}

colossus/apps/lists/templates/lists/base_editor.html
{% extends 'base.html' %}

{% block title %}{{ form_template.get_key_display }}{% endblock %}

{% load colossus i18n %}

{% block javascript %}
  <script>
    $(function () {
      $(".js-save-form").click(function () {
        $("form").submit();
      });
    });
  </script>
{% endblock %}

{% block main %}
  <div class="container-fluid">
    {% include 'includes/messages.html' %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'lists:lists' %}">{% trans 'Mailing Lists' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'lists:list' mailing_list.pk %}">{{ mailing_list.name }}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'lists:subscription_forms' mailing_list.pk %}">{% trans 'Subscription Forms' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'lists:forms_editor' mailing_list.pk %}">{% trans 'Forms Editor' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ form_template.get_key_display }}</li>
      </ol>
    </nav>
    <div class="d-flex justify-content-between align-items-center mb-3">
      <div class="d-flex align-items-center">
        <h6 class="mb-0 mr-3">{% trans 'Forms and response emails' %}</h6>
        <div class="dropdown">
          <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuFormResponsesEmails" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="{{ subscription_forms|get:form_template.key|get:'icon' }} mr-1"></i>
            {{ form_template.get_key_display }}
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuFormResponsesEmails">
            {% for key, options in subscription_forms.items %}
              {% ifchanged %}<h6 class="dropdown-header">{{ workflows.LABELS|get:options.workflow }}</h6>{% endifchanged %}
              <a class="dropdown-item{% if form_template.key == key %} active{% endif %}" href="{% url 'lists:edit_form_template' mailing_list.pk key %}">
                <i class="{{ options.icon }}{% if form_template.key != key %} text-muted{% endif %} mr-1"></i>
                {{ template_keys.LABELS|get:key }}
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
      <nav>
        <form action="{% url 'lists:reset_form_template' mailing_list.pk form_template.key %}" method="post" class="d-inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-link">{% trans 'Reset defaults' %}</button>
        </form>
        <a href="{% url 'lists:customize_design' mailing_list.pk %}" class="btn btn-primary" role="button">{% trans 'Customize base design' %}</a>
        <button type="button" class="btn btn-success js-save-form">{% trans 'Save changes' %}</button>
      </nav>
    </div>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

colossus/apps/lists/templates/lists/import_preview.html
{% extends 'base.html' %}

{% load colossus crispy_forms_tags i18n %}

{% block title %}{% trans 'Confirm import' %}{% endblock %}

{% block stylesheet %}
  <style>
    #tablePreview td,
    #tablePreview th {
      white-space: nowrap;
    }
  </style>
{% endblock %}

{% block javascript %}
  <script>
    // FIXME: Move javascript code to an external .js file
    $(function () {

      var updateTableColumns = function (index) {
        if ($(this).val() === "") {
          $("#tablePreview tbody tr").each(function () {
            $("td", this).eq(index).addClass("table-danger");
          });
        }
        else {
          $("#tablePreview tbody tr").each(function () {
            $("td", this).eq(index).removeClass("table-danger");
          });
        }
      };

      var $columns = $("select[name^='__column_']");

      $columns.each(updateTableColumns);
      $columns.change(function () {
        $("option[value='" + $(this).val() + "']:selected").closest("select").not(this).val("");
        $columns.each(updateTableColumns);
      });

    });
  </script>
{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'lists:lists' %}">{% trans 'Mailing Lists' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'lists:list' mailing_list.pk %}">{{ mailing_list.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'lists:subscribers' mailing_list.pk %}">{% trans 'Subscribers' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'lists:import_subscribers' mailing_list.pk %}">{% trans 'Import Subscribers' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'lists:csv_import_subscribers' mailing_list.pk %}">{% trans 'Import CSV File' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Confirm import' %}</li>
    </ol>
  </nav>
  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title">{% trans 'Confirm import' %}</h2>
      <p class="mb-0">
        <strong>{% trans 'Filename:' %}</strong>
        {{ subscriber_import.file.name }}
      </p>
      <p>
        <strong>{% trans 'Size:' %}</strong>
        {{ subscriber_import.size }} rows
      </p>
      <div class="alert alert-primary">
        <span class="fa fa-info-circle mr-1"></span>
        {% trans 'You may select a custom mapping by changing the table header select values below.' %}
      </div>
      <form action="" method="post">
        {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
              <span class="fa fa-exclamation-triangle mr-1"></span> {{ error }}
            {% endfor %}
          </div>
        {% endif %}
        {% csrf_token %}
        <div class="card mb-3">
          <div class="card-header d-flex justify-content-between align-items-center">
            <div>
              <span class="far fa-file mr-2"></span>
              {{ subscriber_import.file.name }}
            </div>
            <a href="{% url 'lists:download_subscriber_import' mailing_list.pk subscriber_import.pk %}">
              <span class="fas fa-cloud-download-alt"></span>
            </a>
          </div>
          <div class="table-responsive">
            <table class="table table-sm table-striped table-bordered mb-0" id="tablePreview">
              <thead>
                <tr class="table-secondary">
                  {% for field in form.column_mapping_fields %}
                    <th>{{ field }}</th>
                  {% endfor %}
                </tr>
                <tr>
                  {% for header in subscriber_import.get_headings %}
                    <th>{{ header }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
              {% for row in subscriber_import.get_preview %}
                <tr>
                  {% for col in row %}
                    <td>{{ col }}</td>
                  {% endfor %}
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          {% if subscriber_import.size > 10 %}
            <div class="card-footer">
              <p class="card-text text-muted">
                <small>
                  {% trans 'Showing first 10 entries. Total entries in the file:' %} {{ subscriber_import.size }}.
                </small>
              </p>
            </div>
          {% endif %}
        </div>
        <p class="mb-0">
          <small class="text-muted">{% trans 'Email field is mandatory' %}</small>
        </p>
        <p>
          <small class="text-muted">{% trans 'Date format:' %} 2001-12-31 23:59:59</small>
        </p>

        <div class="row">
          <div class="col-8">
            {% for field in form.import_settings_fields %}
              {{ field|as_crispy_field }}
            {% endfor %}
          </div>
        </div>
        <button type="submit" role="button" name="submit" value="import" class="btn btn-success">{% trans 'Confirm import' %}</button>
        <button type="submit" role="button" name="submit" value="save" class="btn btn-outline-success">{% trans 'Save & finish later' %}</button>
        <a href="{% url 'lists:delete_subscriber_import' mailing_list.pk subscriber_import.pk %}" class="btn btn-outline-danger" role="button">{% trans 'Discard' %}</a>
      </form>
    </div>
  </div>
{% endblock %}

colossus/apps/lists/templates/lists/mailinglist_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags i18n %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'lists:lists' %}">{% trans 'Mailing Lists' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'New list' %}</li>
    </ol>
  </nav>
  <div class="card mb-3">
    <div class="card-body">
      <h3 class="card-title">{% trans 'Create a new list' %}</h3>
      <form method="post">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-10 col-lg-6">
            {{ form|crispy }}
          </div>
        </div>
        <button type="submit" class="btn btn-success" role="button">{% trans 'Create list' %}</button>
        <a href="{% url 'lists:lists' %}" class="btn btn-outline-secondary" role="button">{% trans 'Never mind' %}</a>
      </form>
    </div>
  </div>
{% endblock %}