colossus/apps/campaigns/urls.py
from django.urls import path

from . import views

app_name = "campaigns"

urlpatterns = [
    path("", views.CampaignListView.as_view(), name="campaigns"),
    path("add/", views.CampaignCreateView.as_view(), name="campaign_add"),
    path("<int:pk>/", views.CampaignDetailView.as_view(), name="campaign_detail"),
    path(
        "<int:pk>/revert-draft/",
        views.CampaignRevertDraftView.as_view(),
        name="campaign_revert_draft",
    ),
    path(
        "<int:pk>/scheduled/",
        views.CampaignScheduledView.as_view(),
        name="campaign_scheduled",
    ),
    path(
        "<int:pk>/preview/",
        views.CampaignPreviewView.as_view(),
        name="campaign_preview",
    ),
    path(
        "<int:pk>/reports/",
        views.CampaignReportsView.as_view(),
        name="campaign_reports",
    ),
    path(
        "<int:pk>/reports/locations/",
        views.CampaignReportsLocationsView.as_view(),
        name="campaign_reports_locations",
    ),
    path(
        "<int:pk>/reports/locations/<str:country_code>/",
        views.CampaignReportsCountryView.as_view(),
        name="campaign_reports_country",
    ),
    path("<int:pk>/links/", views.CampaignLinksView.as_view(), name="campaign_links"),
    path(
        "<int:pk>/links/<int:link_pk>/edit/",
        views.LinkUpdateView.as_view(),
        name="edit_link",
    ),
    path("<int:pk>/edit/", views.CampaignEditView.as_view(), name="campaign_edit"),
    path(
        "<int:pk>/edit/name/",
        views.CampaignEditNameView.as_view(),
        name="campaign_edit_name",
    ),
    path(
        "<int:pk>/edit/recipients/",
        views.CampaignEditRecipientsView.as_view(),
        name="campaign_edit_recipients",
    ),
    path(
        "<int:pk>/edit/from/",
        views.CampaignEditFromView.as_view(),
        name="campaign_edit_from",
    ),
    path(
        "<int:pk>/edit/subject/",
        views.CampaignEditSubjectView.as_view(),
        name="campaign_edit_subject",
    ),
    path(
        "<int:pk>/edit/content/",
        views.campaign_edit_content,
        name="campaign_edit_content",
    ),
    path(
        "<int:pk>/edit/content/template/",
        views.CampaignEditTemplateView.as_view(),
        name="campaign_edit_template",
    ),
    path(
        "<int:pk>/edit/test-email/",
        views.campaign_test_email,
        name="campaign_test_email",
    ),
    path(
        "<int:pk>/preview-email/",
        views.campaign_preview_email,
        name="campaign_preview_email",
    ),
    path("<int:pk>/send/", views.send_campaign, name="send_campaign"),
    path(
        "<int:pk>/send/done/",
        views.SendCampaignCompleteView.as_view(),
        name="send_campaign_complete",
    ),
    path("<int:pk>/replicate/", views.replicate_campaign, name="replicate_campaign"),
    path(
        "<int:pk>/delete/", views.CampaignDeleteView.as_view(), name="delete_campaign"
    ),
    path(
        "<int:pk>/schedule/",
        views.ScheduleCampaignView.as_view(),
        name="schedule_campaign",
    ),
    path("ajax/load-list-tags/", views.load_list_tags, name="load_list_tags"),
]

colossus/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from colossus.apps.core import views as core_views

urlpatterns = [
    path("", core_views.dashboard, name="dashboard"),
    path("", include("colossus.apps.subscribers.urls", namespace="subscribers")),
    path("setup/", core_views.setup, name="setup"),
    path("setup/account/", core_views.setup_account, name="setup_account"),
    path("settings/", core_views.SiteUpdateView.as_view(), name="settings"),
    path("accounts/", include("colossus.apps.accounts.urls")),
    path("lists/", include("colossus.apps.lists.urls", namespace="lists")),
    path(
        "notifications/",
        include("colossus.apps.notifications.urls", namespace="notifications"),
    ),
    path("templates/", include("colossus.apps.templates.urls", namespace="templates")),
    path("campaigns/", include("colossus.apps.campaigns.urls", namespace="campaigns")),
    path(
        "<slug:mailing_list_slug>/",
        core_views.subscribe_shortcut,
        name="subscribe_shortcut",
    ),
    path(
        "<slug:mailing_list_slug>/unsubscribe/",
        core_views.unsubscribe_shortcut,
        name="unsubscribe_shortcut",
    ),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

colossus/apps/campaigns/models.py
import json
import re
import uuid
from typing import Optional

from django.apps import apps
from django.contrib.sites.shortcuts import get_current_site
from django.db import models, transaction
from django.db.models import Count, QuerySet
from django.template import Context, Template
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import gettext, gettext_lazy as _

from bs4 import BeautifulSoup

from colossus.apps.lists.models import MailingList
from colossus.apps.subscribers.constants import ActivityTypes
from colossus.apps.templates.models import EmailTemplate
from colossus.apps.templates.utils import get_template_blocks

from .constants import CampaignStatus, CampaignTypes
from .tasks import send_campaign_task, update_rates_after_campaign_deletion


class Campaign(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(_("name"), max_length=100)
    campaign_type = models.PositiveSmallIntegerField(
        _("type"), choices=CampaignTypes.CHOICES, default=CampaignTypes.REGULAR
    )
    mailing_list = models.ForeignKey(
        MailingList,
        on_delete=models.CASCADE,
        verbose_name=_("mailing list"),
        related_name="campaigns",
        null=True,
        blank=True,
    )
    tag = models.ForeignKey(
        "subscribers.Tag",
        on_delete=models.SET_NULL,
        verbose_name=_("tag"),
        related_name="campaigns",
        null=True,
        blank=True,
    )
    status = models.PositiveSmallIntegerField(
        _("status"),
        choices=CampaignStatus.CHOICES,
        default=CampaignStatus.DRAFT,
        db_index=True,
    )
    send_date = models.DateTimeField(
        _("send date"), null=True, blank=True, db_index=True
    )
    create_date = models.DateTimeField(_("create date"), auto_now_add=True)
    update_date = models.DateTimeField(_("update date"), default=timezone.now)
    recipients_count = models.PositiveIntegerField(default=0)
    track_opens = models.BooleanField(_("track opens"), default=True)
    track_clicks = models.BooleanField(_("track clicks"), default=True)
    unique_opens_count = models.PositiveIntegerField(
        _("unique opens"), default=0, editable=False
    )
    total_opens_count = models.PositiveIntegerField(
        _("total opens"), default=0, editable=False
    )
    unique_clicks_count = models.PositiveIntegerField(
        _("unique clicks"), default=0, editable=False
    )
    total_clicks_count = models.PositiveIntegerField(
        _("total clicks"), default=0, editable=False
    )
    open_rate = models.FloatField(_("opens"), default=0.0, editable=False)
    click_rate = models.FloatField(_("clicks"), default=0.0, editable=False)

    __cached_email = None

    class Meta:
        verbose_name = _("campaign")
        verbose_name_plural = _("campaigns")
        db_table = "colossus_campaigns"

    def __str__(self):
        return self.name

    def get_absolute_url(self) -> str:
        if self.can_edit:
            return reverse("campaigns:campaign_edit", kwargs={"pk": self.pk})
        elif self.is_scheduled:
            return reverse("campaigns:campaign_scheduled", kwargs={"pk": self.pk})
        return reverse("campaigns:campaign_detail", kwargs={"pk": self.pk})

    def delete(self, using=None, keep_parents=False):
        super().delete(using, keep_parents)
        update_rates_after_campaign_deletion.delay(self.mailing_list_id)

    @property
    def is_scheduled(self) -> bool:
        return self.status == CampaignStatus.SCHEDULED

    @property
    def can_edit(self) -> bool:
        return self.status == CampaignStatus.DRAFT

    @property
    def can_send(self) -> bool:
        for email in self.emails.all():
            if not email.can_send:
                return False
        else:
            return True

    @property
    def email(self) -> Optional["Email"]:
        if not self.__cached_email and self.campaign_type == CampaignTypes.REGULAR:
            try:
                self.__cached_email, created = Email.objects.get_or_create(
                    campaign=self
                )
            except Email.MultipleObjectsReturned:
                self.__cached_email = self.emails.order_by("id").first()
        return self.__cached_email

    def get_recipients(self):
        queryset = self.mailing_list.get_active_subscribers()
        if self.tag is not None:
            queryset = queryset.filter(tags=self.tag)
        return queryset

    def send(self):
        with transaction.atomic():
            self.recipients_count = self.get_recipients().count()
            self.send_date = timezone.now()
            self.status = CampaignStatus.QUEUED
            for email in self.emails.select_related("template").all():
                if email.template is not None:
                    email.template.last_used_date = timezone.now()
                    email.template.last_used_campaign_id = self.pk
                    email.template.save()
            self.save()
        send_campaign_task.delay(self.pk)

    @transaction.atomic
    def replicate(self):
        copy = gettext(" (copy)")
        slice_at = 100 - len(copy)
        name = "%s%s" % (self.name[:slice_at], copy)

        replicated_campaign = Campaign.objects.create(
            name=name,
            campaign_type=self.campaign_type,
            mailing_list=self.mailing_list,
            status=CampaignStatus.DRAFT,
        )

        replicated_emails = list()

        for email in self.emails.all():
            replicated_email = Email(
                campaign=replicated_campaign,
                template=email.template,
                template_content=email.template_content,
                from_email=email.from_email,
                from_name=email.from_name,
                subject=email.subject,
                preview=email.preview,
                content=email.content,
                content_html=email.content_html,
                content_text=email.content_text,
            )
            replicated_emails.append(replicated_email)

        Email.objects.bulk_create(replicated_emails)
        return replicated_campaign

    def update_clicks_count_and_rate(self) -> tuple:
        Activity = apps.get_model("subscribers", "Activity")
        qs = (
            Activity.objects.filter(
                email__campaign=self, activity_type=ActivityTypes.CLICKED
            )
            .values("subscriber_id")
            .order_by("subscriber_id")
            .aggregate(
                unique_count=Count("subscriber_id", distinct=True),
                total_count=Count("subscriber_id"),
            )
        )
        self.unique_clicks_count = qs["unique_count"]
        self.total_clicks_count = qs["total_count"]
        try:
            self.click_rate = self.unique_clicks_count / self.recipients_count
        except ZeroDivisionError:
            self.click_rate = 0.0
        self.save(
            update_fields=["unique_clicks_count", "total_clicks_count", "click_rate"]
        )
        return (self.unique_clicks_count, self.total_clicks_count, self.click_rate)

    def update_opens_count_and_rate(self) -> tuple:
        Activity = apps.get_model("subscribers", "Activity")
        qs = (
            Activity.objects.filter(
                email__campaign=self, activity_type=ActivityTypes.OPENED
            )
            .values("subscriber_id")
            .order_by("subscriber_id")
            .aggregate(
                unique_count=Count("subscriber_id", distinct=True),
                total_count=Count("subscriber_id"),
            )
        )
        self.unique_opens_count = qs["unique_count"]
        self.total_opens_count = qs["total_count"]
        try:
            self.open_rate = self.unique_opens_count / self.recipients_count
        except ZeroDivisionError:
            self.open_rate = 0.0
        self.save(
            update_fields=["unique_opens_count", "total_opens_count", "open_rate"]
        )
        return (self.unique_opens_count, self.total_opens_count, self.open_rate)

    def get_links(self) -> QuerySet:
        """
        A method to list campaign's links

        :return: All links associated with the campaign, ordered by the total number of clicks
        """
        links = Link.objects.filter(email__campaign=self).order_by(
            "-total_clicks_count"
        )
        return links


class Email(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    campaign = models.ForeignKey(
        Campaign,
        on_delete=models.CASCADE,
        verbose_name=_("campaign"),
        related_name="emails",
    )
    template = models.ForeignKey(
        EmailTemplate,
        on_delete=models.SET_NULL,
        verbose_name=_("email template"),
        related_name="emails",
        null=True,
        blank=True,
    )
    template_content = models.TextField(_("email template content"), blank=True)
    from_email = models.EmailField(_("email address"))
    from_name = models.CharField(_("name"), max_length=100, blank=True)
    subject = models.CharField(_("subject"), max_length=150)
    preview = models.CharField(_("preview"), max_length=150, blank=True)
    content = models.TextField(_("content"), blank=True)
    content_html = models.TextField(_("content HTML"), blank=True)
    content_text = models.TextField(_("content plain text"), blank=True)
    unique_opens_count = models.PositiveIntegerField(
        _("unique opens"), default=0, editable=False
    )
    total_opens_count = models.PositiveIntegerField(
        _("total opens"), default=0, editable=False
    )
    unique_clicks_count = models.PositiveIntegerField(
        _("unique clicks"), default=0, editable=False
    )
    total_clicks_count = models.PositiveIntegerField(
        _("total clicks"), default=0, editable=False
    )

colossus/apps/campaigns/templates/campaigns/base.html
{% extends 'base.html' %}

{% load campaigns i18n %}

{% block title %}{{ campaign.name }}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'campaigns:campaigns' %}">{% trans 'Campaigns' %}</a></li>
      {% block breadcrumb %}
      {% endblock %}
    </ol>
  </nav>
  <div class="d-flex justify-content-between align-items-center mb-3">
    <div class="d-flex align-items-center">
      <h2 class="mb-0 mr-2">{{ campaign.name }}</h2>
      <a href="{% url 'campaigns:campaign_edit_name' campaign.pk %}" class="btn btn-sm btn-link" role="button">
        <span class="fa fa-pencil-alt"></span>
        {% trans 'Rename' %}
      </a>
    </div>
    {{ campaign|campaign_status_badge }}
  </div>

  {% block maincontent %}
    <div class="card mb-3">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link{% if submenu == 'details' %} active{% endif %}" href="{% url 'campaigns:campaign_detail' campaign.pk %}">{% trans 'Details' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if submenu == 'preview' %} active{% endif %}" href="{% url 'campaigns:campaign_preview' campaign.pk %}">{% trans 'Campaign Preview' %}</a>
          </li>
          {% if campaign.track_clicks %}
            <li class="nav-item">
              <a class="nav-link{% if submenu == 'links' %} active{% endif %}" href="{% url 'campaigns:campaign_links' campaign.pk %}">{% trans 'Links' %}</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link{% if submenu == 'reports' %} active{% endif %}" href="{% url 'campaigns:campaign_reports' campaign.pk %}">{% trans 'Reports' %}</a>
          </li>
        </ul>
      </div>
      {% block innercontent %}
      {% endblock %}
    </div>
    {% block outercontent %}
    {% endblock outercontent %}
  {% endblock maincontent %}
{% endblock %}

colossus/apps/campaigns/templates/campaigns/campaign_edit.html
{% extends 'base.html' %}

{% load campaigns crispy_forms_tags i18n %}

{% block title %}{{ campaign.name }}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'campaigns:campaigns' %}">{% trans 'Campaigns' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ campaign.name }}</li>
    </ol>
  </nav>
  <div class="card mb-3">
    <div class="card-body d-flex justify-content-between align-items-center">
      <h2 class="mb-0">{{ campaign.name }} <small class="text-muted">#{{ campaign.id }}</small></h2>
      {{ campaign|campaign_status_badge }}
    </div>
    <ul class="list-group list-group-flush">

      <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if campaign.mailing_list %}
          <div class="d-flex align-items-center">
            <i data-feather="check-circle" class="mr-3 text-success"></i>
            <div>
              <h5 class="mb-1">{% trans 'To' %}</h5>
              <p class="mb-1">
                {% if campaign.tag %}
                  {% blocktrans trimmed with campaign.mailing_list.name as name and campaign.tag.name as tag_name %}
                    Subscribers in the list <strong>{{ name }}</strong> with tag <span class="badge badge-primary">{{ tag_name }}</span>.
                  {% endblocktrans %}
                {% else %}
                  {% blocktrans trimmed with campaign.mailing_list.name as name %}
                    All subscribers in the list <strong>{{ name }}</strong>.
                  {% endblocktrans %}
                {% endif %}
              </p>
              <p class="mb-0">
                <a href="javascript:void(0);">{% blocktrans trimmed with campaign.get_recipients.count as count %}{{ count }} recipients{% endblocktrans %}</a>.
              </p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_recipients' campaign.pk %}" role="button" class="btn btn-outline-secondary">{% trans 'Edit recipients' %}</a>
        {% else %}
          <div class="d-flex align-items-center">
            <i data-feather="circle" class="mr-3 text-muted"></i>
            <div>
              <h5 class="mb-1">{% trans 'To' %}</h5>
              <p class="text-muted font-italic mb-0">{% trans 'Who are you sending this campaign to?' %}</p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_recipients' campaign.pk %}" role="button" class="btn btn-secondary">{% trans 'Add recipients' %}</a>
        {% endif %}
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if campaign.email.from_email %}
          <div class="d-flex align-items-center">
            <i data-feather="check-circle" class="mr-3 text-success"></i>
            <div>
              <h5 class="mb-1">{% trans 'From' %}</h5>
              <p class="mb-0">{{ campaign.email.get_from }}</p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_from' campaign.pk %}" role="button" class="btn btn-outline-secondary">{% trans 'Edit from' %}</a>
        {% else %}
          <div class="d-flex align-items-center">
            <i data-feather="circle" class="mr-3 text-muted"></i>
            <div>
              <h5 class="mb-1">{% trans 'From' %}</h5>
              <p class="text-muted font-italic mb-0">{% trans 'Who is sending this campaign?' %}</p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_from' campaign.pk %}" role="button" class="btn btn-secondary">{% trans 'Add from' %}</a>
        {% endif %}
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if campaign.email.subject %}
          <div class="d-flex align-items-center">
            <i data-feather="check-circle" class="mr-3 text-success"></i>
            <div>
              <h5 class="mb-1">{% trans 'Subject' %}</h5>
              <p class="mb-0">{{ campaign.email.subject }}</p>
              {% if campaign.email.preview %}<small class="text-muted">Preview: {{ campaign.email.preview }}</small>{% endif %}
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_subject' campaign.pk %}" role="button" class="btn btn-outline-secondary">{% trans 'Edit subject' %}</a>
        {% else %}
          <div class="d-flex align-items-center">
            <i data-feather="circle" class="mr-3 text-muted"></i>
            <div>
              <h5 class="mb-1">{% trans 'Subject' %}</h5>
              <p class="text-muted font-italic mb-0">{% trans "What's the subject line for this campaign?" %}</p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_subject' campaign.pk %}" role="button" class="btn btn-secondary">{% trans 'Add subject' %}</a>
        {% endif %}
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if campaign.email.content %}
          <div class="d-flex align-items-center">
            <i data-feather="check-circle" class="mr-3 text-success"></i>
            <div>
              <h5 class="mb-1">{% trans 'Content' %}</h5>
              <div>
                <a href="javascript:void(0);" data-toggle="modal" data-target="#previewEmailModal">{% trans 'Preview Email' %}</a>
                ・
                <a href="javascript:void(0);" data-toggle="modal" data-target="#sendTestEmailModal">{% trans 'Send Test Email' %}</a>
              </div>
            </div>
          </div>
          <div>
              <p class="mb-0">
                <small class="text-muted">
                  {% if checklist.unsub %}
                    <i data-feather="check" class="text-success" style="height:15px;vertical-align:middle;"></i>
                    {% trans 'Email contains unsubscribe link.' %}
                  {% else %}
                    <i data-feather="x" class="text-danger" style="height:15px;vertical-align:middle;"></i>
                    {% trans 'Unsubscribe link not found.' %} <a href="{% url 'campaigns:campaign_edit_content' campaign.pk %}">{% trans 'Resolve' %}</a>
                  {% endif %}
                </small>
              </p>
          </div>
          <a href="{% url 'campaigns:campaign_edit_content' campaign.pk %}" role="button" class="btn btn-outline-secondary">{% trans 'Edit design' %}</a>
        {% else %}
          <div class="d-flex align-items-center">
            <i data-feather="circle" class="mr-3 text-muted"></i>
            <div>
              <h5 class="mb-1">{% trans 'Content' %}</h5>
              <p class="text-muted font-italic mb-0">{% trans 'Design the content for your email.' %}</p>
            </div>
          </div>
          <a href="{% url 'campaigns:campaign_edit_content' campaign.pk %}" role="button" class="btn btn-secondary">{% trans 'Design email' %}</a>
        {% endif %}
      </li>

    </ul>
    <div class="card-footer d-flex justify-content-between">
      <div>
        {% if campaign.can_send %}
          <a href="{% url 'campaigns:send_campaign' campaign.pk %}" class="btn btn-primary" role="button">{% trans 'Send campaign' %}</a>
          <a href="{% url 'campaigns:schedule_campaign' campaign.pk %}" class="btn btn-outline-primary" role="button">{% trans 'Schedule' %}</a>
        {% else %}
          <a href="#" class="btn btn-primary disabled" tabindex="-1" role="button" aria-disabled="true">{% trans 'Send campaign' %}</a>
          <a href="#" class="btn btn-outline-primary disabled" tabindex="-1" role="button" aria-disabled="true">{% trans 'Schedule' %}</a>
        {% endif %}
        <a href="{% url 'campaigns:campaigns' %}" class="btn btn-outline-secondary" role="button">{% trans 'Finish later' %}</a>
      </div>
      <a href="{% url 'campaigns:delete_campaign' campaign.pk %}" class="btn btn-outline-danger" role="button">{% trans 'Discard' %}</a>
    </div>
  </div>

  <div class="modal fade" id="sendTestEmailModal" tabindex="-1" role="dialog" aria-labelledby="sendTestEmailModalLabel" aria-hidden="true">
    <form method="post" action="{% url 'campaigns:campaign_test_email' campaign.pk %}">
      {% csrf_token %}
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="sendTestEmailModalLabel">{% trans 'Send test email' %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ test_email_form|crispy }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% trans 'Never mind' %}</button>
            <button type="submit" class="btn btn-success">{% trans 'Send email' %}</button>
          </div>
        </div>
      </div>
    </form>
  </div>

  <div class="modal fade" id="previewEmailModal" tabindex="-1" role="dialog" aria-labelledby="previewEmailMdalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="previewEmailMdalLabel">{% trans 'Preview email' %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body p-0">
          <iframe src="{% url 'campaigns:campaign_preview_email' campaign.pk %}" class="w-100" style="min-height:500px; border: 0 none;"></iframe>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

colossus/apps/campaigns/templates/campaigns/campaign_edit_recipients.html
{% extends 'base.html' %}

{% load crispy_forms_filters i18n %}

{% block title %}{% trans 'Recipients' %}{% endblock %}

{% block javascript %}
  <script>
    $(function () {
      $("#id_mailing_list").change(function () {
        var $form = $(this).closest("form");
        var listId = $(this).val();
        $.ajax({
          url: $form.data("load-list-tags-url"),
          data: {
            'id': listId
          },
          success: function (data) {
            $("#id_tag").html(data.options);
          }
        });
      });
    });
  </script>
{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'campaigns:campaigns' %}">{% trans 'Campaigns' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'campaigns:campaign_edit' campaign.pk %}">{{ campaign.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Recipients' %}</li>
    </ol>
  </nav>
  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title">{% trans 'Recipients' %}</h2>
      <form method="post" data-load-list-tags-url="{% url 'campaigns:load_list_tags' %}" novalidate>
        {% csrf_token %}
        <div class="form-row">
          <div class="col">
            {{ form.mailing_list|as_crispy_field }}
          </div>
          <div class="col">
            {{ form.tag|as_crispy_field }}
          </div>
        </div>
        <button type="submit" class="btn btn-success" role="button">{% trans 'Save changes' %}</button>
        <a href="{{ campaign.get_absolute_url }}" class="btn btn-outline-secondary" role="button">{% trans 'Never mind' %}</a>
      </form>
    </div>
  </div>
{% endblock %}

colossus/apps/campaigns/templates/campaigns/campaign_preview.html
{% extends 'campaigns/base.html' %}

{% load i18n %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'campaigns:campaign_detail' campaign.pk %}">{{ campaign.name }}</a></li>
  <li class="breadcrumb-item active" aria-current="page">{% trans 'Preview' %}</li>
{% endblock %}

{% block innercontent %}
  <div class="card-body">
    <iframe src="{% url 'campaigns:campaign_preview_email' campaign.pk %}" class="w-100" style="min-height:500px; border: 0 none;"></iframe>
  </div>
{% endblock %}